version: '3.4'

networks:
  vnetbackend:  

services:
  backendcrud.minimal.api:
    container_name: crudminimalapi2024
    image: ${DOCKER_REGISTRY-}backendcrudminimalapi
    build:
      context: .
      dockerfile: BackendCRUD.Minimal.Api/Dockerfile
    environment:
      - DB_SERVER_HOST=servicio_contenedorbd
      - DB_SERVER_PORT=1433
      - DB_NAME=BD_Team
      - DB_USER=sa
      - DB_SA_PASSWORD=Password1*      
    networks:
      - vnetbackend
    ports:
      - "12000:8082"
    depends_on:
      - servicio_contenedorbd 
  servicio_contenedorbd:
    container_name: dbcontainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1*
    networks:
      - vnetbackend
    ports:
        - "8001:1433"