USE [master]
go
IF EXISTS (SELECT * from dbo.sysobjects where id=OBJECT_ID('TEMP_DATA_BD_Team ')) 
	DROP TABLE master.dbo.TEMP_DATA_BD_Team  

DECLARE @PATH_DATOS  VARCHAR(200)      

set @PATH_DATOS   = 'C:\MSSQL_BD'     /* IMPORTANTE: THIS FOLDER MUST BE PREVIOSLY CREATED!! */

/************************************************************************/
SET NOCOUNT ON;
USE [master]
CREATE TABLE TEMP_DATA_BD_Team  (path_datos varchar(200))
INSERT INTO TEMP_DATA_BD_Team  (path_datos) 
    VALUES (@PATH_DATOS)

DECLARE  @PATH_DATOS2 VARCHAR(200)
SELECT  @PATH_DATOS2=path_datos from master.dbo.TEMP_DATA_BD_Team 
EXECUTE('CREATE DATABASE [BD_Team] ON  PRIMARY 
( NAME = ''BD_Team '', FILENAME = '''+ @PATH_DATOS2+'\BD_Team .mdf'' , SIZE = 200000KB , MAXSIZE = 1GB, FILEGROWTH = 512000KB )
 LOG ON 
( NAME = ''BD_Team _Log'', FILENAME = '''+ @PATH_DATOS2+'\BD_Team .ldf'' , SIZE = 200000KB , MAXSIZE = 1GB , FILEGROWTH = 10%)
');
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'BD_Team ', @new_cmptlevel=130    /* IMPORTANTE: NIVEL 130 de Compatibility ES PARA SQL SERVER 2016 o SUPERIOR!! */
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Team].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [BD_Team] SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE [BD_Team] SET ANSI_NULLS OFF
ALTER DATABASE [BD_Team] SET ANSI_PADDING OFF
ALTER DATABASE [BD_Team] SET ANSI_WARNINGS OFF
ALTER DATABASE [BD_Team] SET ARITHABORT OFF
ALTER DATABASE [BD_Team] SET AUTO_CLOSE OFF
ALTER DATABASE [BD_Team] SET AUTO_CREATE_STATISTICS ON
ALTER DATABASE [BD_Team] SET AUTO_SHRINK OFF
ALTER DATABASE [BD_Team] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [BD_Team] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [BD_Team] SET CURSOR_DEFAULT  GLOBAL
ALTER DATABASE [BD_Team] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [BD_Team] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [BD_Team] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [BD_Team] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [BD_Team] SET  DISABLE_BROKER
ALTER DATABASE [BD_Team] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [BD_Team] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [BD_Team] SET TRUSTWORTHY OFF
ALTER DATABASE [BD_Team] SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE [BD_Team] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [BD_Team] SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE [BD_Team] SET  READ_WRITE
ALTER DATABASE [BD_Team] SET RECOVERY SIMPLE
ALTER DATABASE [BD_Team] SET  MULTI_USER
ALTER DATABASE [BD_Team] SET PAGE_VERIFY CHECKSUM
ALTER DATABASE [BD_Team] SET DB_CHAINING OFF
GO
